/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import com.example.model.Client;
import jakarta.persistence.Persistence;

public class App {

    public static void main(String[] args) {
        System.out.println("App started");

        var emf = Persistence.createEntityManagerFactory("pu");
        var em = emf.createEntityManager();

        var query = em.createQuery("from " + Client.class.getName() + " c where c.name='one'", Client.class);
        var entity = query.getSingleResult();
        System.out.println(entity);

        System.out.println("App finished");
    }
}
