/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import com.example.model.Client;
import jakarta.persistence.Persistence;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class AppTest {
    @Test
    public void test() {
        var emf = Persistence.createEntityManagerFactory("pu");
        var em = emf.createEntityManager();

        var query = em.createQuery("from " + Client.class.getName() + " c where c.name='one'", Client.class);
        var entity = query.getSingleResult();

        assertThat(entity).isNotNull();
        assertThat(entity.id).isEqualTo(1L);
    }
}
